<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Timothy" name="freddie.data.NewAccountTest" tests="1" failures="0" timestamp="08 Dec 2017 02:59:02 GMT" time="0.641" errors="1">
  <testcase name="test" time="0.641" classname="freddie.data.NewAccountTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.testng.internal.reflect.ReflectionRecipes.isInstanceOf(ReflectionRecipes.java:71)
	at org.testng.internal.reflect.ReflectionRecipes.exactMatch(ReflectionRecipes.java:248)
	at org.testng.internal.reflect.ReflectionRecipes.exactMatch(ReflectionRecipes.java:233)
	at org.testng.internal.reflect.DirectMethodMatcher.match(DirectMethodMatcher.java:37)
	at org.testng.internal.reflect.AbstractNodeMethodMatcher.hasConformance(AbstractNodeMethodMatcher.java:26)
	at org.testng.internal.reflect.AbstractMethodMatcher.conforms(AbstractMethodMatcher.java:27)
	at org.testng.internal.reflect.DataProviderMethodMatcher.hasConformance(DataProviderMethodMatcher.java:24)
	at org.testng.internal.reflect.AbstractMethodMatcher.conforms(AbstractMethodMatcher.java:27)
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:40)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1301)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1195)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- freddie.data.NewAccountTest -->
